### PR TITLE
Fix hang in X11 borderless mode

### LINKED ISSUE #87: Blank screen when running in openbox
Hi I'm trying to start `flex-launcher` using openbox on NixOS with X11

If I use the following openbox auto start script
```bash
#!${pkgs.bash}/bin/bash
# End all lines with '&' to not halt startup script execution
flex-launcher &
```
Nothing happens but I can see that the `flex-launcher` process is running using `ps -ef | grep flex`.

But if I change the auto start script to
```bash
#!${pkgs.bash}/bin/bash
# End all lines with '&' to not halt startup script execution
xterm &
flex-launcher &
```

It starts working, what am I missing here? Are there any logs I can view to narrow this down?

### PR DESCRIPTION
**Pull request by ludocode**
Fixes #87

### CODE REVIEW

File: src/launcher.c [hunk 1]
```diff
@@ -221,7 +221,7 @@ static void create_window()
                  SDL_WINDOWPOS_UNDEFINED,
                  0,
                  0,
-                 SDL_WINDOW_FULLSCREEN_DESKTOP | SDL_WINDOW_BORDERLESS
+                 SDL_WINDOW_FULLSCREEN_DESKTOP
```
Comment (ludocode) [inline src/launcher.c]: See #87 for an explanation of what I think is going on. `SDL_WINDOW_BORDERLESS` is redundant; `SDL_WINDOW_FULLSCREEN_DESKTOP` already means borderless.

**Comment by AnderssonPeter** [comment]
@complexlogic are there any plans to release a new version that includes this fix?

**Comment by complexlogic** [comment]
@AnderssonPeter Sure I can do that
